[package]
name = "mmds"
version = "0.1.2"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>", "Rrogntudju"]
edition = "2018"

[dependencies]
static_init = "1"
serde_json = "1"
warp = "0.3"
tokio = {version = "1", features = ["macros"]} 
