[package]
name = "mmds"
version = "0.1.1"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>", "Rrogntudju"]
edition = "2018"

[dependencies]
lazy_static = "1"
serde_json = "1"
warp = "0.2"
tokio = {version = "0.2", features = ["macros"]} 
