[package]
name = "warp-mds"
version = "0.1.2"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
warp = "0.3"
mmds = {path = "../mmds"}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
